[package]
name = "mac_specs"
version = "0.1.0"
authors = ["Joseph Lyons <JosephTLyons@users.noreply.github.com>"]
edition = "2021"

[dependencies]
os_type = "2.0.0"
sys-info = "0.5.6"
users = "0.7.0"
